# Report structure
:trello_sources:
  board_syseng:
    :board_id: "55b8e03be0b7b68131139cf1"
    :lists: 
      :in_progress: "55b8e064fb3f1d621db0746f"
      :backlog: "55b8e05ebda5066e15c24025"
      :investigation: "55b8e83c1df82cf0bbd4edba"
      :completed: "55b8e4428ec04b31597cd5c3"
  board_e2e:
    :board_id: "5640b810860935a27a6139d6"
    :lists:
      :backlog: "5640bb2965cec07628642994"
      :next: "5640bb2ac2110e0628dde44a"
      :in_progress: "5640bb2c9826d99d92fbfd7b"
:tags:
  funding_buckets:
    :tag_prefix: "fb_"
    :pretty_name: "Funding Bucket"
  project:
    :tag_prefix: "project_"
    :pretty_name: "Project"
  team:
    :tag_prefix: "team_"
    :pretty_name: "Team"
  type:
    :tag_prefix: "type_"
    :pretty_name: "Type"
:columns:
  1:
    :name: "Assignment ID"
    :key: "id"
  2:
    :name: "Assignment"
    :key: "name"
  3:
    :name: "Owner"
    :key: "members"
  4:
    :name: "Project"
    :key: "project"
  5:
    :name: "Funding Buckets"
    :key: "funding_buckets"
  6:
    :name: "Status"
    :key: "status"
  7:
    :name: "Last Updated"
    :key: "last_updated"
  8:
    :name: "Detailed Status"
    :key: "detailed_status"
  9:
    :name: "Tags"
    :key: "tags"
  10:
    :name: "Short URL"
    :key: "short_url"
  11:
    :name: "Board"
    :key: "board_name"
  12:
    :name: "List"
    :key: "list_name"
  13:
    :name: "Team"
    :key: "team"
  14:
    :name: "Type"
    :key: "type"
  15:
    :name: "Last Moved"
    :key: "latest_move"
  16:
    :name: "Due Date"
    :key: "due_date"
