# Report structure
:trello_sources:
  board_syseng:
    :board_id: "55b8e03be0b7b68131139cf1"
    :lists: 
      :in_progress: "55b8e064fb3f1d621db0746f"
      :backlog: "55b8e05ebda5066e15c24025"
      :investigation: "55b8e83c1df82cf0bbd4edba"
      :completed: "55b8e4428ec04b31597cd5c3"
  board_e2e:
    :board_id: "5640b810860935a27a6139d6"
    :lists:
      :backlog: "5640bb2965cec07628642994"
      :next: "5640bb2ac2110e0628dde44a"
      :in_progress: "5640bb2c9826d99d92fbfd7b"
:tags:
  funding_buckets:
    :tag_prefix: "fb_"
    :pretty_name: "Funding Bucket"
  project:
    :tag_prefix: "project_"
    :pretty_name: "Project"
  team:
    :tag_prefix: "team_"
    :pretty_name: "Team"
  type:
    :tag_prefix: "type_"
    :pretty_name: "Type"
:columns:
  1:
    :name: "Assignment ID"
    :key: "id"
  2:
    :name: "Assignment"
    :key: "name"
  3:
    :name: "Owner"
    :key: "member"
  project:
    :name: "Project"
    :line_key: "project"
  funding_buckets:
    :name: "Funding Buckets"
    :line_key: "funding_buckets"
  status:
    :name: "Status"
    :line_key: "status"
  last_updated:
    :name: "Last Updated"
    :line_key: "last_updated"
  detailed_status:
    :name: "Detailed Status"
    :line_key: "detailed_status"
  tags:
  short_url:
  board_name:
  list_name:
  team:
  type:
  last_moved:
  due_date:

