#https://trello.com/1/appKey/generate
##https://trello.com/1/connect?key=<appKey>&name=OpenShift&response_type=token&scope=read,write,account
##https://trello.com/1/connect?key=<appKey>&name=OpenShift&response_type=token&scope=read,write,account&expiration=never
#---
:consumer_key: <consumer_key>
:consumer_secret: <consumer_secret>
:oauth_token: <oauth_token>
:oauth_token_secret: <oauth_secret>

